name: Coordify
options:
  bundleIdPrefix: net.yuuan
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"
targets:
  Coordify:
    type: application
    platform: macOS
    sources:
      - Coordify
    settings:
      base:
        INFOPLIST_FILE: Coordify/Info.plist
        CODE_SIGN_ENTITLEMENTS: Coordify/Coordify.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: net.yuuan.Coordify
        PRODUCT_NAME: Coordify
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: BWK37MJZ59
        CODE_SIGN_IDENTITY: "Apple Development"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
  CoordifyTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - CoordifyTests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: Coordify
schemes:
  Coordify:
    build:
      targets:
        Coordify: all
        CoordifyTests: [test]
    test:
      targets:
        - CoordifyTests
